### ISSUE TITLE
Cloud sync/online account

### ISSUE THREAD

**Issue by NovaPlasm** [acgrobman/presense#13]
#### Description
As a teacher, I would like my saved data to be synced to an online account so that my data isn't tied to one phone (if it breaks, etc.)

#### Type
User story

#### Task list
- [x] Set up mongodb(or other) database
- [x] Determine what tables other than user accounts we want
- [x] Create all tables and columns
- [x] Create interface between app and database
