### ISSUE TITLE
Open the app

### ISSUE THREAD

**Issue by NovaPlasm** [acgrobman/presense#3]
#### Description
As a user, I would like to be able to open the app so that I can access features inside

#### Type
User story

#### Task list
- [x] Setup developer environment for React Native [Potentially helpful tutorial](https://facebook.github.io/react-native/docs/getting-started.html)
- [x] Generate empty project
- [x] Make a basic Hello World screen
- [x] Load it onto the phone
- [x] ????
- [x] Profit

**Comment by NovaPlasm** [comment]
Closed in recent pull request
